server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 1234

  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    format-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  # log 설정
  logging:
    pattern:
      console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    level:
      org:
        hibernate:
          SQL: debug
          type.descriptor.sql: trace

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

jwt:
  secret-key:
  expiration-hours: 24
  issuer:

paypal:
  baseUrl: https://api-m.sandbox.paypal.com
  clientId:
  clientSecret:

iamport:
  api:
    url:
    key:
    secret: